### ISSUE TITLE
Apple M1 / ARM Support

### ISSUE THREAD

**Issue by dennispost** [veertuinc/packer-plugin-veertu-anka#107]
On Apple M1 / ARM I'm getting 
`invalid remote binary packer-plugin-veertu-anka_v2.2.0_x5.0_darwin_amd64.zip: wrong system, expected darwin_arm64` 
when installing the plugin using `packer init`.

Please create a release for Apple M1 / ARM.

**Comment by NorseGaud** [comment]
2.3.0 is now available
