### ISSUE TITLE
Feature Request: Add option to distribute after push

### ISSUE THREAD

**Issue by wilrnh** [veertuinc/packer-plugin-veertu-anka#117]
Hi I'd like to request adding an option to the veertu-anka-registry-push plugin that tells the controller to distribute the template to the nodes.

This would help us automate distributing templates to our nodes after packer builds, which is something that we manually take advantage of to speed up builds.

Some options:
`distribute`: distribute the template to all nodes
`node-ids`: specific nodes to distribute to
`group-ids`: specific groups to distribute to

**Comment by Esysc** [comment]
Very nice feature to add indeed.
I don't know how this may work, the registry is not actively involved in the plugin as far as I understand. The build runs on a mac host, the post-processor then can or can not push to a remote registry. I don't know if there is an API that can talk to the registry at this level. The only possible thing that comes in my mind is to interact with the registry rest API via a `post-processor "local-shell"` step.

**Comment by NorseGaud** [comment]
For now, this is relatively easy to achieve by making an API call with a `local-shell` or script outside of packer/our plugin. Supporting calls to the controller would be a decent amount of new code and complexity, so I will close this for now. If we get more requests like this, we can reopen.
