### ISSUE TITLE
Feature Request: Add support for network configuration

### ISSUE THREAD

**Issue by sanieldalib** [veertuinc/packer-plugin-veertu-anka#118]
Currently configuring the network on a VM must be manually done. It would be great if support could be added, especially for the `--local / --no-local` flag to ` enable/disable inter-VM and VM-host communication`.

**Comment by NorseGaud** [comment]
Hey @sanieldalib, we're going to close this as it's possible currently using a local shell provisioner in packer and execute the anka modify command against the newly created VM template.
