### ISSUE TITLE
Error when upgrading packer plugin

### ISSUE THREAD

**Issue by n3rdc4ptn** [veertuinc/packer-plugin-veertu-anka#125]
When I upgrade the packer plugin using the command `packer init -upgrade` I always get the following error:
```bash
❯ packer init -upgrade build-vm.pkr.hcl
Failed getting the "github.com/veertuinc/veertu-anka" plugin:
1 error occurred:
        * could not get sha256 checksum file for github.com/veertuinc/veertu-anka version 2.3.2. Is the file present on the release and correctly named ? GET https://github.com/veertuinc/packer-plugin-veertu-anka/releases/download/v2.3.2/packer-plugin-veertu-anka_v2.3.2_SHA256SUMS: 404  []
```

After checking the Release page, I saw that the latest packer release has some difference between the previous one.
![Bildschirm­foto 2022-08-08 um 10 43 31](https://user-images.githubusercontent.com/16562869/183377626-3b4ac9d3-abb4-4900-a03f-764bfde21177.png)

Could you maybe change the name of the latest release and remove the x5.0 in the shasums ?

**Comment by Esysc** [comment]
@NorseGaud it seems it had wrongly named the checksum file.

**Comment by NorseGaud** [comment]
Got it, try now! Sorry about that

**Comment by NorseGaud** [comment]
Keeping this open because we need a test to catch this in the automation. I'll try to add it in the next release

**Comment by NorseGaud** [comment]
The checksum files won't have the API version on them.
