### ISSUE TITLE
"Failed to pull" error when template does not already exist on the node running packer

### ISSUE THREAD

**Issue by tejassharma96** [veertuinc/packer-plugin-veertu-anka#161]
Currently when we run a `veertu-anka-vm-clone` provisioner with just a template name but no tag, if the template is not already pulled on the node it spits out the following:
```
==> veertu-anka-vm-clone.anka-macos-from-source: Pulling source VM m1-macos-13.5-pm with tag latest from Anka Registry
2023/08/28 14:25:22 packer-plugin-veertu-anka_v3.2.0_x5.0_darwin_arm64 plugin: 2023/08/28 14:25:22 Executing anka --machine-readable registry pull --tag latest m1-macos-13.5-pm
==> veertu-anka-vm-clone.anka-macos-from-source: failed to pull vm m1-macos-13.5-pm with tag latest from registry (make sure to add it as the default: https://docs.veertu.com/anka/intel/command-line-reference/#registry-add)
```

it is trying to pull the vm with the literal tag `"latest"`. I believe it should instead leave off the tag argument if one is not supplied, which will automatically pull the actual latest version of that template.

**Comment by NorseGaud** [comment]
Yep, looks like it's hard coded to `latest`. Easy fix. will work on a release ASAP

**Comment by NorseGaud** [comment]
- Updated to use packer 0.5.1 and upgraded go-cty and hcl per https://github.com/hashicorp/packer-plugin-sdk/issues/188
- https://github.com/veertuinc/packer-plugin-veertu-anka/issues/161
