### ISSUE TITLE
Add the ability to handle "expect_disconnect" in provisioner

### ISSUE THREAD

**Issue by jerrymarino** [veertuinc/packer-plugin-veertu-anka#21]
Packer supports the ability to handle `"expect_disconnect"`. This is useful to restart macOS catalina during a build of packer.

As of today, when I attempt to shutdown macOS in a packer template for anka I get this:

```

veertu-anka: -anka: communication broken
--
  | veertu-anka: Shutdown NOW!
  | veertu-anka:
  | veertu-anka: System shutdown time has arrived

```

**Comment by NorseGaud** [comment]
Hey @jerrymarino, I've talked with our developers and they say this can be added. I've opened the ticket on our end and will notify you once we determine which release it will be a part of.

**Comment by NorseGaud** [comment]
Hey @jerrymarino, this seems to work for me in our v1.6.0 branch using:

```json
{
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "set -x",
        "sudo reboot",
        "echo SHOULD NOT SEE THIS ECHO"
      ],
      "expect_disconnect": true
    },
    {
      "type": "shell",
      "inline": [
        "set -x",
        "echo REBOOTED"
      ]
    }
  ],
  "builders": [{
    "type": "veertu-anka",
    "source_vm_name": "10.15.6"
  }]
}
```

We'll be releasing it in the next few days.

**Comment by NorseGaud** [comment]
Was able to reproduce this in CI/CD. We'll take a further look.

**Comment by NorseGaud** [comment]
Out of ~420 runs, we were finally able to reproduce this locally. Investigation is ongoing.

**Comment by NorseGaud** [comment]
Known issue with IP changes: https://github.com/hashicorp/packer/issues/10175

**Comment by NorseGaud** [comment]
In 2.1.0 expect_disconnect is working as expected. There is an extremely rare situation where anka will not reboot properly, but the changes of that are slim. Closing this for now.
