### ISSUE TITLE
VM fails to reboot

### ISSUE THREAD

**Issue by petemounce** [veertuinc/packer-plugin-veertu-anka#48]
I'm using 1.6.0 packer plugin, with Anka 2.3.0 (Build Lite on mac mini, Flow on macbook pro). I'm using packer to build from a known-good installer.app for macOS 10.15.7.

When I run a packer build on my laptop in this context, it passes.

When I run a packer build on the mac mini in this context, it fails with an error (apologies for screenshot!) `error on reboot` after it finishes with the `Converting to anka format` step. The VM is then deleted, so I cannot inspect it.

![WhatsApp Image 2020-11-30 at 16 32 10 (1)](https://user-images.githubusercontent.com/69720/100942208-d1b59380-34f2-11eb-9f3e-94b779b31b5c.jpeg)

**Comment by NorseGaud** [comment]
Hey @petemounce 

1. How often can you reproduce this?
2. Can you upgrade to 2.3.1 for us as 2.3.0 has a few instabilities and then confirm if it happens again?

**Comment by NorseGaud** [comment]
This is unable to be reproduced in the latest Anka version.
