### ISSUE TITLE
Feature Request: Option to delete base VM after building

### ISSUE THREAD

**Issue by tejassharma96** [veertuinc/packer-plugin-veertu-anka#63]
For my team's use case, we only need to use packer to create a single vm for each version of macOS. The base vm that gets created is unnecessary and means I have to go in manually and delete it. Not a very high priority request, but would be nice to have.

**Comment by NorseGaud** [comment]
@tejassharma96 , can you clarify this a bit for me? What are you seeing?

**Comment by tejassharma96** [comment]
uhhh this is from 2 years ago and I don't remember what this was in relation to. we're able to use packer fine now, so feel free to close.
