### ISSUE TITLE
Feature-request: allow setting the display controller

### ISSUE THREAD

**Issue by odormond** [veertuinc/packer-plugin-veertu-anka#72]
We would like to have packer able to do an `anka modify VM_ID set display -c pg` to enable the support for metal on Big Sur.

See: https://veertu.com/build-and-test-metal-xcode-projects-with-anka/

**Comment by NorseGaud** [comment]
Totally agree! We'll add it to the backlog for v2.0.0 (see the branches)

**Comment by odormond** [comment]
Looks like this finally missed v2.0.0 release. At least I haven't found mention of it in the readme. Any chance it will be included in v2.1.0?

**Comment by NorseGaud** [comment]
Sorry about that. 2.0.0 ended up being so large that we wanted to minimize the changes in it to high-priority items. We'll fit this into v2.1.0 which is being worked on right now.

**Comment by NorseGaud** [comment]
Hey @odormond , just wanted to confirm that you were able to work around this in the meantime by using a `shell-local` provisioned. 2.1.0 is likely going to be another week or so.
