### ISSUE TITLE
Feature-request: Upgrade to use the new RPC server

### ISSUE THREAD

**Issue by JamesForsee** [veertuinc/packer-plugin-veertu-anka#73]
As of Packer 1.7.0, Packer now has the ability to pull required plugins using the "packer init" command.

Plugins must upgrade by following [this guide](https://www.packer.io/guides/1.7-plugin-upgrade#upgrade-plugins-to-use-the-new-multi-component-rpc-server) in order to take advantage of the tooling.

This upgrade will require renaming the repository to the new "packer-plugin-*" convention and switch to using a semantic versioning system without the prefacing "v", so it may be a non-starter but I wanted to put it on the radar.

**Comment by JamesForsee** [comment]
Thanks for the quick feedback @NorseGaud, I'm not familiar with Go but I did take a quick look at the PR. I am super excited about the ability to push and pull templates as part of the packer build. 
Version 2.0.0 will be a huge workflow improvement for our team, can't wait for this!!!

**Comment by NorseGaud** [comment]
Hey @JamesForsee , 2.0.0 has been released. 

I'm not entirely sure I understand the way to use packer init and it looks like we tag using v in the tag name. Can you see if it works for you now?

**Comment by JamesForsee** [comment]
@NorseGaud I gave it a test and was unsuccessful to pull the plugin using packer init in the current state.
I added a PR with a fix to this and instructions to follow for the repo maintainer. 

A new release v2.0.1 will need to be released in order to pick up the changes

**Comment by NorseGaud** [comment]
Sorry it took so long @JamesForsee , but it looks to be working. 2.1.10 has been released: https://github.com/veertuinc/packer-plugin-veertu-anka/releases/tag/v2.1.0
